#ifndef __CONSTANTS_INCLUDED__
#define __CONSTANTS_INCLUDED__
#define IP_LEN 16
#define ETH_ALEN 6
#define PURGE_TIMEOUT 10000
#define PORT_ENTRY_TIMEOUT 10000
#define ETH_HDR_LEN 14
#define ODR_HDR_LEN 64
#define PORT_MAX 65535
//#define TIME_SERV_PORT 5800
#endif
